import defaultTheme from 'tailwindcss/defaultTheme';

/** @type {import('tailwindcss').Config} */
export default {
    content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
    darkMode: 'selector', // will apply dark mode (all elements with `dark:` perfix) only if the `dark` class is present in the `html` tag
    theme: {
        extend: {
            colors: {
                text: {
                    50: 'var(--text-50)',
                    100: 'var(--text-100)',
                    200: 'var(--text-200)',
                    300: 'var(--text-300)',
                    400: 'var(--text-400)',
                    500: 'var(--text-500)',
                    600: 'var(--text-600)',
                    700: 'var(--text-700)',
                    800: 'var(--text-800)',
                    900: 'var(--text-900)',
                    950: 'var(--text-950)',
                },
                background: {
                    50: 'var(--background-50)',
                    100: 'var(--background-100)',
                    200: 'var(--background-200)',
                    300: 'var(--background-300)',
                    400: 'var(--background-400)',
                    500: 'var(--background-500)',
                    600: 'var(--background-600)',
                    700: 'var(--background-700)',
                    800: 'var(--background-800)',
                    900: 'var(--background-900)',
                    950: 'var(--background-950)',
                },
                primary: {
                    50: 'var(--primary-50)',
                    100: 'var(--primary-100)',
                    200: 'var(--primary-200)',
                    300: 'var(--primary-300)',
                    400: 'var(--primary-400)',
                    500: 'var(--primary-500)',
                    600: 'var(--primary-600)',
                    700: 'var(--primary-700)',
                    800: 'var(--primary-800)',
                    900: 'var(--primary-900)',
                    950: 'var(--primary-950)',
                },
                secondary: {
                    50: 'var(--secondary-50)',
                    100: 'var(--secondary-100)',
                    200: 'var(--secondary-200)',
                    300: 'var(--secondary-300)',
                    400: 'var(--secondary-400)',
                    500: 'var(--secondary-500)',
                    600: 'var(--secondary-600)',
                    700: 'var(--secondary-700)',
                    800: 'var(--secondary-800)',
                    900: 'var(--secondary-900)',
                    950: 'var(--secondary-950)',
                },
                accent: {
                    50: 'var(--accent-50)',
                    100: 'var(--accent-100)',
                    200: 'var(--accent-200)',
                    300: 'var(--accent-300)',
                    400: 'var(--accent-400)',
                    500: 'var(--accent-500)',
                    600: 'var(--accent-600)',
                    700: 'var(--accent-700)',
                    800: 'var(--accent-800)',
                    900: 'var(--accent-900)',
                    950: 'var(--accent-950)',
                },
            },
            container: {
                center: true,
                screens: {
                    'pc-lg': '1680px',
                    'pc-md': '1440px',
                    'pc-sm': '1280px',
                    'tablet-lg': '1024px',
                    'tablet-md': '768px',
                    'tablet-sm': '640px',
                    'mobile-lg': '480px',
                    'mobile-md': '375px',
                    'mobile-sm': '320px',
                },
            },
        },
        screens: {
            // a "desktop-first" approach (larger screens first and smaller screens later)
            'pc-lg': { max: '1679px' },
            'pc-md': { max: '1439px' },
            'pc-sm': { max: '1279px' },
            'tablet-lg': { max: '1023px' },
            'tablet-md': { max: '767px' },
            'tablet-sm': { max: '639px' },
            'mobile-lg': { max: '479px' },
            'mobile-md': { max: '374px' },
            'mobile-sm': { max: '319px' },

            'max-2xl': { max: '1535px' },
            'max-xl': { max: '1279px' },
            'max-lg': { max: '1023px' },
            'max-md': { max: '767px' },
            'max-sm': { max: '639px' },
            ...defaultTheme.screens,
        },
    },
    plugins: ['tailwind-scrollbar'],
};
